a = input("var1 : ")
b = input("var1 : ")
c = input("var1 : ")
d = input("var2 : ")
e = input("var2 : ")
f = input("var2 : ")
g = input("var3 : ")
h = input("var3 : ")
i = input("var3 : ")
j = input("var4 : ")
k = input("var4 : ")
l = input("var4 : ")
m = input("var5 : ")
n = input("var5 : ")
o = input("var5 : ")

print("HASIL = %s,%s,%s,n1,%s,%s,%s,n2,%s,%s,%s,n3,%s,%s,%s,n4,%s,%s,%s,n5,%s,%s,%s,n1,%s,%s,%s,n2,%s,%s,%s,n3,%s,%s,%s,n4,%s,%s,%s,n5,%s,%s,%s,n1,%s,%s,%s,n2,%s,%s,%s,n3,%s,%s,%s,n4,%s,%s,%s,n5,%s,%s,%s,n1,%s,%s,%s,n2,%s,%s,%s,n3,%s,%s,%s,n4,%s,%s,%s,n5,%s,%s,%s,n1,%s,%s,%s,n2,%s,%s,%s,n3,%s,%s,%s,n4,%s,%s,%s,n5,"%(a,b,c,a,b,c,a,b,c,a,b,c,a,b,c,d,e,f,d,e,f,d,e,f,d,e,f,d,e,f,g,h,i,g,h,i,g,h,i,g,h,i,g,h,i,j,k,l,j,k,l,j,k,l,j,k,l,j,k,l,m,n,o,m,n,o,m,n,o,m,n,o,m,n,o,))
